# Generated by Django 4.0.3 on 2022-06-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='ratings',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
